database:
    driverClass: org.h2.Driver
    user: sa
    password: sa
    url: jdbc:h2:./errortest;FILE_LOCK=NO
    maxWaitForConnection: 2s
    minSize: 1
    maxSize: 10
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.hbm2ddl.import_files: sample.sql
